services:
  # FastAPI Backend
  - type: web
    name: va-calibration-api
    runtime: python
    region: oregon
    plan: free
    branch: main
    rootDir: api
    buildCommand: "pip install poetry && poetry install --without dev"
    startCommand: "poetry run uvicorn app.main_direct:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: REDIS_URL
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: CELERY_BROKER_URL
        sync: false
      - key: CELERY_RESULT_BACKEND
        sync: false
    healthCheckPath: /

  # Celery Worker (deployed as web service for free tier compatibility)
  - type: web
    name: va-calibration-worker
    runtime: python
    region: oregon
    plan: free
    branch: main
    rootDir: api
    buildCommand: "pip install poetry && poetry install --without dev"
    startCommand: "bash start_worker.sh"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: REDIS_URL
        sync: false
      - key: CELERY_BROKER_URL
        sync: false
      - key: CELERY_RESULT_BACKEND
        sync: false

  # React Frontend (Static Site)
  - type: web
    name: va-calibration-frontend
    runtime: static
    branch: main
    rootDir: mock-to-real
    buildCommand: "npm install && npm run build"
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: "20.11.0"
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: va-calibration-api
          property: host
