version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: vacalib-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

  api:
    build: .
    container_name: vacalib-api
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - ../data:/app/data:ro
      - ./app:/app/app
    restart: unless-stopped

  worker:
    build: .
    container_name: vacalib-worker
    command: celery -A app.celery_app worker --loglevel=info --concurrency=2
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - ../data:/app/data:ro
      - ./app:/app/app
    restart: unless-stopped

  beat:
    build: .
    container_name: vacalib-beat
    command: celery -A app.celery_app beat --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - ../data:/app/data:ro
      - ./app:/app/app
    restart: unless-stopped

volumes:
  redis_data: